package com.oreilly.hh.data;
// Generated 2014-8-13 15:25:47 by Hibernate Tools 3.2.0.beta6a


import com.oreilly.hh.SourceMedia;
import com.oreilly.hh.StereoVolume;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Track generated by hbm2java
 */
public class Track  implements java.io.Serializable {

    // Fields    

     private int id;
     private String title;
     private String filePath;
     /**
      * playing time
     */
     private Date playTime;
     private Set<Artist> artists = new HashSet<Artist>(0);
     /**
      * when the track was created
     */
     private Date added;
     /**
      * how loud to play the track
     */
     private StereoVolume volume;
     /**
      * Media on which track was obtained
     */
     private SourceMedia sourceMedia;
     private Set<String> comments = new HashSet<String>(0);

     // Constructors

    /** default constructor */
    public Track() {
    }

	/** minimal constructor */
    public Track(String title, String filePath) {
        this.title = title;
        this.filePath = filePath;
    }
    /** full constructor */
    public Track(String title, String filePath, Date playTime, Set<Artist> artists, Date added, StereoVolume volume, SourceMedia sourceMedia, Set<String> comments) {
       this.title = title;
       this.filePath = filePath;
       this.playTime = playTime;
       this.artists = artists;
       this.added = added;
       this.volume = volume;
       this.sourceMedia = sourceMedia;
       this.comments = comments;
    }
    
   
    // Property accessors
    public int getId() {
        return this.id;
    }
    
    protected void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    /**       
     *      * playing time
     */
    public Date getPlayTime() {
        return this.playTime;
    }
    
    public void setPlayTime(Date playTime) {
        this.playTime = playTime;
    }
    public Set<Artist> getArtists() {
        return this.artists;
    }
    
    public void setArtists(Set<Artist> artists) {
        this.artists = artists;
    }
    /**       
     *      * when the track was created
     */
    public Date getAdded() {
        return this.added;
    }
    
    public void setAdded(Date added) {
        this.added = added;
    }
    /**       
     *      * how loud to play the track
     */
    public StereoVolume getVolume() {
        return this.volume;
    }
    
    public void setVolume(StereoVolume volume) {
        this.volume = volume;
    }
    /**       
     *      * Media on which track was obtained
     */
    public SourceMedia getSourceMedia() {
        return this.sourceMedia;
    }
    
    public void setSourceMedia(SourceMedia sourceMedia) {
        this.sourceMedia = sourceMedia;
    }
    public Set<String> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<String> comments) {
        this.comments = comments;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("title").append("='").append(getTitle()).append("' ");			
      buffer.append("volume").append("='").append(getVolume()).append("' ");			
      buffer.append("sourceMedia").append("='").append(getSourceMedia()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }



}


